services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    command: ["mongod", "--port", "27005", "--bind_ip_all"]
    ports:
      - "27005:27005"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: accounting-system-backend:latest
    environment:
      - MONGODB_URI=mongodb://mongo:27005/velosync
    depends_on:
      - mongo
    ports:
      - "4005:4005"

  frontend:
    build: .
    image: accounting-system-frontend:latest
    ports:
      - "8005:80"
    depends_on:
      - backend

volumes:
  mongo-data:
