import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import path from 'path';
import 'express-async-errors';
import authRoutes from './routes/auth';
import clientsRoutes from './routes/clients';
import uploadsRoutes from './routes/uploads';
import swaggerRoutes from './routes/swagger';
import config from './config';
const app = express();
app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use('/auth', authRoutes);
app.use('/clients', clientsRoutes);
app.use('/uploads', uploadsRoutes);
app.use('/docs', swaggerRoutes);
app.use('/uploads', express.static(path.join(process.cwd(), config.UPLOADS_DIR)));
app.use((err:any, req:any, res:any, next:any)=> { console.error(err); res.status(500).json({ error: err.message }); });
export default app;
