import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh';

export interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translations: Record<Language, Translations>;
  updateTranslation: (lang: Language, key: string, value: string) => void;
}

const defaultTranslations: Record<Language, Translations> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.masters': 'Masters',
    'nav.clients': 'Clients',
    'nav.vendors': 'Vendors',
    'nav.banks': 'Banks',
    'nav.taxConfig': 'Tax Config',
    'nav.bookkeeping': 'Bookkeeping',
    'nav.invoices': 'Invoices',
    'nav.expenses': 'Expenses',
    'nav.transactions': 'Transactions',
    'nav.financialReports': 'Financial Reports',
    'nav.taxReports': 'Tax Reports (IRD)',
    'nav.salary': 'Salary',
    'nav.employees': 'Employees',
    'nav.payroll': 'Payroll',
    'nav.users': 'Users',
    'nav.userGuide': 'User Guide',
    'nav.translations': 'Translations',
    'nav.approvals': 'Approvals',
    'nav.vatReports': 'VAT Reports',
    'nav.employeePortal': 'Employee Portal',
    'nav.settings': 'Settings',
    'nav.signOut': 'Sign Out',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and application settings',
    'settings.profile': 'Profile',
    'settings.changePassword': 'Change Password',
    'settings.company': 'Company',
    'settings.defaults': 'Defaults',
    'settings.emailConfig': 'Email',
    'settings.profileInfo': 'Profile Information',
    'settings.fullName': 'Full Name',
    'settings.profileEmail': 'Email',
    'settings.role': 'Role',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',
    'settings.companyInfo': 'Company Information',
    'settings.companyName': 'Company Name',
    'settings.taxNumber': 'Tax Registration Number',
    'settings.companyAddress': 'Company Address',
    'settings.companyPhone': 'Phone Number',
    'settings.companyEmail': 'Email',
    'settings.currency': 'Default Currency',
    'settings.dateFormat': 'Date Format',
    'settings.fiscalYearStart': 'Fiscal Year Start',
    'settings.defaultSettings': 'Default Settings',
    'settings.paymentTerms': 'Default Payment Terms (days)',
    'settings.invoiceDueDays': 'Invoice Due Days',
    'settings.defaultCurrency': 'Default Currency',
    'settings.stampFee': 'Stamp Fee (LKR)',
    'settings.preferences': 'Preferences',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Send email notifications for important events',
    'settings.autoApprove': 'Auto-approve Admin Transactions',
    'settings.autoApproveDesc': 'Automatically approve transactions created by admin users',
    'settings.emailConfiguration': 'Email Configuration',
    
    // Pending Approval Page
    'pending.title': 'Account Pending Approval',
    'pending.message': 'Your account has been created successfully. Please wait for an administrator to assign your role before you can access the system.',
    'pending.loggedAs': 'Logged in as',
    'pending.contactAdmin': 'If you believe this is an error, please contact your system administrator.',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.description': 'Description',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.applyFilter': 'Apply Filter',
    'common.filterByDate': 'Filter by Date',
    'common.startDate': 'Start Date',
    'common.endDate': 'End Date',
    'common.showing': 'Showing data from',
    'common.to': 'to',
    'common.select': 'Select',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': "Welcome back! Here's your financial overview.",
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalExpenses': 'Total Expenses',
    'dashboard.netProfit': 'Net Profit',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.payroll': 'Payroll',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.fromDate': 'From Date',
    'dashboard.toDate': 'To Date',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.financialSummary': 'Financial Summary',
    'dashboard.createInvoice': 'Create Invoice',
    'dashboard.createInvoiceDesc': 'Generate a new invoice for clients',
    'dashboard.recordExpense': 'Record Expense',
    'dashboard.recordExpenseDesc': 'Log a new business expense',
    'dashboard.processPayroll': 'Process Payroll',
    'dashboard.processPayrollDesc': 'Generate and manage employee payroll',
    'dashboard.viewReports': 'View Reports',
    'dashboard.viewReportsDesc': 'Analyze your financial data',
    'dashboard.revenue': 'Revenue',
    'dashboard.expenses': 'Expenses',
    'dashboard.filterByDate': 'Filter by Date',
    'dashboard.startDate': 'Start Date',
    'dashboard.endDate': 'End Date',
    'dashboard.applyFilter': 'Apply Filter',
    'dashboard.clear': 'Clear',
    'dashboard.showingDataFrom': 'Showing data from',
    'dashboard.to': 'to',
    'dashboard.noFinancialData': 'No financial data available',
    
    // Clients
    'clients.title': 'Clients',
    'clients.description': 'Manage your client information',
    'clients.addClient': 'Add Client',
    'clients.editClient': 'Edit Client',
    'clients.clientName': 'Client Name',
    'clients.contactPerson': 'Contact Person',
    
    // Vendors
    'vendors.title': 'Vendors',
    'vendors.description': 'Manage your vendor information',
    'vendors.addVendor': 'Add Vendor',
    'vendors.editVendor': 'Edit Vendor',
    'vendors.vendorName': 'Vendor Name',
    
    // Banks
    'banks.title': 'Bank Accounts',
    'banks.addBank': 'Add Bank Account',
    'banks.editBank': 'Edit Bank Account',
    'banks.bankName': 'Bank Name',
    'banks.accountName': 'Account Name',
    'banks.accountNumber': 'Account Number',
    'banks.branch': 'Branch',
    'banks.balance': 'Current Balance',
    'banks.balanceReadonly': 'Balance is readonly when editing. Update through transactions.',
    
    // Invoices
    'invoices.title': 'Invoices',
    'invoices.addInvoice': 'Add Invoice',
    'invoices.editInvoice': 'Edit Invoice',
    'invoices.invoiceNumber': 'Invoice Number',
    'invoices.client': 'Client',
    'invoices.dueDate': 'Due Date',
    'invoices.paid': 'Paid',
    'invoices.pending': 'Pending',
    'invoices.draft': 'Draft',
    'invoices.files': 'Files',
    'invoices.createInvoice': 'Create Invoice',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.addExpense': 'Add Expense',
    'expenses.editExpense': 'Edit Expense',
    'expenses.category': 'Category',
    'expenses.vendor': 'Vendor',
    'expenses.approved': 'Approved',
    'expenses.pending': 'Pending',
    'expenses.expenseNo': 'Expense #',
    'expenses.files': 'Files',
    
    // Employees
    'employees.title': 'Employees',
    'employees.addEmployee': 'Add Employee',
    'employees.editEmployee': 'Edit Employee',
    'employees.employeeName': 'Employee Name',
    'employees.designation': 'Designation',
    'employees.basicSalary': 'Basic Salary',
    'employees.epfNo': 'EPF No',
    'employees.employeeId': 'Employee ID',
    'employees.department': 'Department',
    
    // Payroll
    'payroll.title': 'Payroll',
    'payroll.generatePayroll': 'Generate Payroll',
    'payroll.processPayroll': 'Process Payroll',
    'payroll.payrollRuns': 'Payroll Runs',
    'payroll.month': 'Month',
    'payroll.year': 'Year',
    'payroll.grossSalary': 'Gross Salary',
    'payroll.netSalary': 'Net Salary',
    'payroll.deductions': 'Deductions',
    'payroll.transportAllowance': 'Transport Allowance',
    'payroll.performanceSalary': 'Performance Salary',
    'payroll.description': 'Generate and manage payroll runs for employees',
    'payroll.runNumber': 'Run #',
    'payroll.period': 'Period',
    'payroll.ctc': 'CTC',
    'payroll.status': 'Status',
    'payroll.attendanceData': 'Attendance Data',
    'payroll.downloadTemplate': 'Download Template',
    'payroll.workingDaysInMonth': 'Working Days in Month',
    'payroll.uploadAttendance': 'Upload Attendance File',
    'payroll.chooseFile': 'Choose Excel file',
    'payroll.attendanceLoaded': 'Loaded attendance for {count} employees',
    'payroll.daysAttended': 'Days Attended',
    'payroll.absent': 'Absent',
    'payroll.attendanceDeduction': 'Attend. Ded.',
    'payroll.otherDeduction': 'Other Ded.',
    'payroll.uploadAttendanceFirst': 'Please upload an attendance file before proceeding',
    'payroll.attendanceWarnings': 'Attendance Warnings',
    'payroll.attendanceHistoryTitle': 'Previous Attendance Records',
    'payroll.attendanceHistoryNote': 'This shows attendance from the last payroll run for this period.',
    'payroll.loadingHistory': 'Loading attendance history...',
    'payroll.employee': 'Employee',
    'payroll.workingDays': 'Working Days',
    'payroll.sickLeave': 'Sick Leave',
    'payroll.casualLeave': 'Casual Leave',
    'payroll.annualLeave': 'Annual Leave',
    'payroll.unpaidLeave': 'Unpaid Leave',
    'payroll.otherLeave': 'Other Leave',
    'payroll.leaveNotes': 'Leave Notes',
    'payroll.leaveBreakdown': 'Leave Breakdown',
    'payroll.paidLeave': 'Paid Leave',
    
    // Users
    'users.title': 'User Management',
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.fullName': 'Full Name',
    'users.role': 'Role',
    'users.admin': 'Admin',
    'users.accountant': 'Accountant',
    'users.employee': 'Employee',
    'users.unmarked': 'Unmarked',
    'users.unmarkedUsersReminder': 'Action Required: Assign User Roles',
    'users.unmarkedUsersMessage': 'user(s) are waiting for role assignment. Please assign roles to enable their access.',
    'users.pending': 'pending',
    'users.pleaseAssignRole': 'Please assign a role to this user',
    'users.passwordHint': 'leave blank to keep current',
    'users.linkEmployee': 'Link to Employee',
    'users.linkEmployeeHint': 'Only employees without linked accounts are shown',
    'users.rolePermissionsTitle': 'Role Permissions',
    'users.usersCount': 'users',
    'users.rolePermissions.fullAccess': 'Full system access',
    'users.rolePermissions.manageUsers': 'Manage users and roles',
    'users.rolePermissions.taxConfig': 'Tax configuration',
    'users.rolePermissions.employees': 'Employee management',
    'users.rolePermissions.payroll': 'Payroll processing',
    'users.rolePermissions.approvals': 'Approve transactions',
    'users.rolePermissions.invoices': 'Create and manage invoices',
    'users.rolePermissions.expenses': 'Record and manage expenses',
    'users.rolePermissions.reports': 'View financial reports',
    'users.rolePermissions.clients': 'Manage clients and vendors',
    'users.rolePermissions.banks': 'View bank accounts',
    'users.rolePermissions.viewPayslips': 'View own payslips',
    'users.rolePermissions.viewProfile': 'View personal profile',
    'users.rolePermissions.requestUpdates': 'Request profile updates',
    'users.editPermissions': 'Edit Permissions',
    'users.addPermission': 'Add permission...',
    'users.resetToDefaults': 'Reset to Defaults',
    'users.confirmResetPermissions': 'Reset all permissions to defaults?',
    'users.selectPermissions': 'Select Permissions',
    'users.customPermissions': 'Custom Permissions',
    'users.addCustomPermission': 'Add custom permission...',
    'users.permissionsSelected': 'permissions selected',
    
    // Vendors
    'vendors.taxId': 'Tax ID',
    
    // Translations
    'translations.title': 'Translation Management',
    'translations.key': 'Key',
    'translations.english': 'English',
    'translations.chinese': 'Chinese (Simplified)',
    'translations.searchPlaceholder': 'Search translations...',
    'translations.saveChanges': 'Save Changes',
    'translations.resetToDefault': 'Reset to Default',
    'translations.saved': 'Translations saved successfully',
    'translations.language': 'Language',
    
    // Login
    'login.title': 'Sign In',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.forgotPassword': 'Forgot Password?',
    'login.accounts': 'Accounts',
    'login.tagline1': 'Streamline Your',
    'login.tagline2': 'Financial Management',
    'login.description': 'Complete accountancy solution with invoicing, expenses, payroll, and tax compliance - all in one platform.',
    'login.createAccount': 'Create Account',
    'login.welcomeBack': 'Welcome Back',
    'login.signupSubtitle': 'Start managing your finances today',
    'login.loginSubtitle': 'Sign in to continue to your dashboard',
    'login.enterFullName': 'Enter your full name',
    'login.creatingAccount': 'Creating account...',
    'login.signingIn': 'Signing in...',
    'login.haveAccount': 'Already have an account?',
    'login.noAccount': "Don't have an account?",
    'login.signInInstead': 'Sign in instead',
    'login.createAccountLink': 'Create an account',
    'login.allRightsReserved': 'All rights reserved.',
    
    // Forgot Password
    'forgotPassword.title': 'Forgot Password?',
    'forgotPassword.subtitle': 'Enter your email to receive a reset link',
    'forgotPassword.resetYour': 'Reset Your',
    'forgotPassword.password': 'Password',
    'forgotPassword.description': "Don't worry, it happens to the best of us. Enter your email and we'll send you a reset link.",
    'forgotPassword.sendResetLink': 'Send Reset Link',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.emailSent': 'Email Sent!',
    'forgotPassword.checkInbox': 'Check your inbox for the password reset link. The link will expire in 1 hour.',
    'forgotPassword.backToLogin': 'Back to Login',
    'forgotPassword.error': 'Failed to send reset email. Please try again.',
    
    // Reset Password
    'resetPassword.title': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password below',
    'resetPassword.createNew': 'Create New',
    'resetPassword.password': 'Password',
    'resetPassword.description': "Choose a strong password that you haven't used before.",
    'resetPassword.newPassword': 'New Password',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.resetPassword': 'Reset Password',
    'resetPassword.resetting': 'Resetting...',
    'resetPassword.success': 'Password Reset!',
    'resetPassword.redirecting': 'Your password has been reset successfully. Redirecting to login...',
    'resetPassword.error': 'Failed to reset password. The link may have expired.',
    'resetPassword.passwordMismatch': 'Passwords do not match',
    'resetPassword.passwordTooShort': 'Password must be at least 8 characters',
    'resetPassword.invalidLink': 'Invalid Reset Link',
    'resetPassword.invalidLinkDescription': 'This password reset link is invalid or has expired.',
    'resetPassword.requestNewLink': 'Request New Link',
    'login.loginFailed': 'Login failed. Please check your email and password.',
    'login.signupFailed': 'Signup failed. Please try again.',
    
    // Guide
    'guide.title': 'User Guide',
    'guide.gettingStarted': 'Getting Started',
    'guide.gettingStartedContent': 'Welcome to VeloSync! This comprehensive accounting system helps you manage all financial operations including clients, invoices, expenses, payroll, and reporting. Use the navigation menu to access different modules based on your role permissions.',
    'guide.managingClients': 'Managing Clients',
    'guide.managingClientsContent': 'Create and manage client records with complete contact information including name, email, phone, address, and tax ID. Navigate to Clients page to add new clients, edit existing records, or delete clients no longer needed. Client records are used when creating invoices.',
    'guide.managingVendors': 'Managing Vendors',
    'guide.managingVendorsContent': 'Maintain vendor records for all suppliers and service providers. Add vendor details including name, contact person, email, phone, and address. Vendors can be linked to expenses for better expense tracking and reporting.',
    'guide.bankAccounts': 'Bank Accounts',
    'guide.bankAccountsContent': 'Set up and manage multiple bank accounts with account numbers, bank names, and branch details. Track opening balances (set only during creation). When a bank account is created with an initial balance, it is recorded as an income transaction. Bank balances are automatically updated when processing invoices, expenses, and payroll.',
    'guide.creatingInvoices': 'Creating Invoices',
    'guide.creatingInvoicesContent': 'Generate professional invoices with automatic serial numbers (INV-XXXX). Add multiple line items with descriptions, quantities, rates, and tax percentages. Attach supporting documents like quotations and receipts. When marking an invoice as paid, select the bank account to credit.',
    'guide.trackingExpenses': 'Tracking Expenses',
    'guide.trackingExpensesContent': 'Record business expenses with automatic serial numbers (EXP-XXXX). Categorize expenses, link to vendors, specify payment method (cash/bank/card), and upload bills and receipts. When approving expenses with bank payment, select the bank account.',
    'guide.employeeManagement': 'Employee Management (Admin Only)',
    'guide.employeeManagementContent': 'Manage employee records including personal details, employment information, and salary components. Set basic salary and allowances. EPF rates and ETF rate are automatically populated from active tax configurations. Set the APIT scenario for each employee.',
    'guide.payrollProcessing': 'Payroll Processing (Admin Only)',
    'guide.payrollProcessingContent': 'Process payroll for multiple employees in bulk. Select employees and preview calculations before processing. In the preview, you can edit Allowances and Performance Bonus. Payroll includes EPF, ETF, APIT, and stamp fees.',
    'guide.apitScenarios': 'APIT Scenarios Explained',
    'guide.apitScenariosContent': 'APIT (Advance Personal Income Tax) is calculated once per employee using slab-based tax brackets with standard deductions. Scenario A - Employee pays APIT (deducted from salary), Scenario B - Employer pays APIT (added to employer costs).',
    'guide.taxConfiguration': 'Tax Configuration (Admin Only)',
    'guide.taxConfigurationContent': 'Configure tax rates including EPF employee rate, EPF employer rate, ETF rate, and stamp fee. These configurations are automatically applied when adding new employees.',
    'guide.taxReports': 'Tax Reports',
    'guide.taxReportsContent': 'Generate tax compliance reports for submission to the Inland Revenue Department. Reports include: gross income from paid invoices, total expenses from approved items, APIT deductions, and payroll statutory contributions.',
    'guide.transactionsTracking': 'Transactions Tracking',
    'guide.transactionsTrackingContent': 'View all financial transactions in one place with two tabs: All Transactions shows invoices, expenses, and payroll summary. Bank Transactions tab displays all bank debits and credits.',
    'guide.financialReports': 'Financial Reports',
    'guide.financialReportsContent': 'Access three comprehensive report views: Overview (total income, expenses, profit), Profit & Loss Statement, and Expenses Breakdown. Reports include only confirmed transactions.',
    'guide.userManagement': 'User Management (Admin Only)',
    'guide.userManagementContent': 'Manage system users with role-based access control. Create users with Admin or Accountant roles. Admin users have full access. Accountant users have restricted access.',
    'guide.fileAttachments': 'File Attachments',
    'guide.fileAttachmentsContent': 'Upload supporting documents for invoices (attachments and receipts) and expenses (bills and receipts). Files are stored securely. When deleting invoices or expenses, associated files are automatically removed.',
    'guide.auditLogs': 'Audit Logs',
    'guide.auditLogsContent': 'All create, update, and delete operations are automatically logged with user information and timestamps. Audit logs help track changes and maintain accountability.',
    'guide.employeePortal': 'Employee Portal',
    'guide.employeePortalContent': 'Employees can access a self-service portal to view payslips, tax documents, and manage personal information. Employees can self-register using their Employee ID and email, or admins can create accounts and link them to employee records. Profile updates require admin approval.',
    'guide.payrollApprovalWorkflow': 'Payroll Approval Workflow',
    'guide.payrollApprovalWorkflowContent': 'Accountants can create payroll runs which require admin approval before processing. Admin users can approve or reject submitted payroll. Once approved, payroll can be processed which creates expense records for statutory contributions and updates bank balances.',
    'guide.attendanceTracking': 'Attendance Tracking',
    'guide.attendanceTrackingContent': 'Upload employee attendance via Excel file before processing payroll. Template includes Employee ID, Name, Working Days, Attended Days with half-day support. System validates data and calculates attendance-based deductions automatically. Leave types include Sick, Casual, Annual, Unpaid, and Other.',
    'guide.vatFiling': 'VAT Filing',
    'guide.vatFilingContent': 'Generate VAT returns for IRD submission. VAT is fixed at 18%. System tracks VAT on invoices and generates VAT returns showing Output VAT (sales), Input VAT (purchases), and Net VAT Payable.',
    'guide.approvalWorkflows': 'Approval Workflows',
    'guide.approvalWorkflowsContent': 'Invoices and expenses created by accountants require admin approval. Admin-created transactions are auto-approved. The Approvals page (admin only) shows all pending items for review. Payroll runs by accountants also require admin approval.',
    'guide.rolePermissions': 'Role Permissions',
    'guide.rolePermissionsContent': 'Admins can customize permissions for each role (Admin, Accountant, Employee) through User Management. Add, remove, or edit permissions dynamically without code changes. Reset to defaults if needed.',
    'guide.multiLanguage': 'Multi-Language Support',
    'guide.multiLanguageContent': 'Switch between English and Chinese using the language selector. Admins can manage translations through the Translation Management page to update UI labels without code changes.',
    'guide.passwordRecovery': 'Password Recovery',
    'guide.passwordRecoveryContent': 'Use the "Forgot Password?" link on the login page to receive a password reset email. Click the link in the email to set a new password. Reset links expire after 1 hour.',
    
    // Tax Configuration
    'taxConfig.title': 'Tax Configurations',
    'taxConfig.addConfig': 'Add Tax Config',
    'taxConfig.editConfig': 'Edit Tax Config',
    'taxConfig.seedDefault': 'Seed Default Configs',
    'taxConfig.seeding': 'Seeding...',
    'taxConfig.type': 'Type',
    'taxConfig.taxType': 'Tax Type',
    'taxConfig.rate': 'Rate',
    'taxConfig.from': 'From',
    'taxConfig.to': 'To',
    'taxConfig.applicableFrom': 'Applicable From',
    'taxConfig.applicableTo': 'Applicable To (Optional)',
    'taxConfig.active': 'Active',
    'taxConfig.inactive': 'Inactive',
    'taxConfig.noConfigs': 'No tax configurations found. Click "Seed Default Configs" to load Sri Lankan defaults.',
    
    // Tax Reports
    'taxReports.title': 'Tax Reports (IRD)',
    'taxReports.generateReport': 'Generate Report',
    'taxReports.companyName': 'Company Name',
    'taxReports.companyTIN': 'Tax Identification Number (TIN)',
    'taxReports.companyAddress': 'Company Address',
    'taxReports.generating': 'Generating...',
    'taxReports.downloadPDF': 'Download Tax Report PDF',
    'taxReports.infoText': 'This will generate a comprehensive tax report including income, expenses, VAT, and payroll tax information for the selected period. The report can be submitted to the Sri Lanka Inland Revenue Department.',
    
    // Transactions Page
    'transactions': 'Transactions',
    'totalIncome': 'Total Income',
    'totalExpenses': 'Total Expenses',
    'totalPayroll': 'Total Payroll',
    'netBalance': 'Net Balance',
    'allTransactions': 'All Transactions',
    'bankTransactions': 'Bank Transactions',
    'all': 'All',
    'income': 'Income',
    'expenses': 'Expenses',
    'payroll': 'Payroll',
    'date': 'Date',
    'type': 'Type',
    'category': 'Category',
    'description': 'Description',
    'reference': 'Reference',
    'amount': 'Amount',
    'bankAccount': 'Bank Account',
    'credit': 'Credit',
    'debit': 'Debit',
    'expense': 'Expense',
    
    // Reports Page
    'reports': 'Reports',
    'reports.title': 'Reports',
    'overviewReport': 'Overview Report',
    'overviewReportDesc': 'Financial summary and key metrics',
    'profitLoss': 'Profit & Loss',
    'profitLossDesc': 'Detailed P&L statement',
    'expenseBreakdown': 'Expense Breakdown',
    'expenseBreakdownDesc': 'Expenses by category',
    'generate': 'Generate',
    'startDate': 'Start Date',
    'endDate': 'End Date',
    
    // Enhanced Reports Page
    'enhancedReports.overview': 'Overview',
    'enhancedReports.profitLoss': 'Profit & Loss',
    'enhancedReports.expensesBreakdown': 'Expenses Breakdown',
    'enhancedReports.totalRevenue': 'Total Revenue',
    'enhancedReports.invoices': 'invoices',
    'enhancedReports.totalExpenses': 'Total Expenses',
    'enhancedReports.expensesLabel': 'Expenses',
    'enhancedReports.payrollCosts': 'Payroll Costs',
    'enhancedReports.payrollEntries': 'payroll entries',
    'enhancedReports.totalCosts': 'Total Costs',
    'enhancedReports.expensesPlusPayroll': 'Expenses + Payroll',
    'enhancedReports.netProfit': 'Net Profit',
    'enhancedReports.profit': 'Profit',
    'enhancedReports.loss': 'Loss',
    'enhancedReports.revenue': 'Revenue',
    'enhancedReports.period': 'Period',
    'enhancedReports.unknown': 'Unknown',
    'enhancedReports.totalPayroll': 'Total Payroll',
    'enhancedReports.netProfitLoss': 'Net Profit/Loss',
    'enhancedReports.count': 'Count',
    'enhancedReports.totalAmount': 'Total Amount',
    'enhancedReports.percentage': 'Percentage',
    'enhancedReports.total': 'Total',
    
    // Approvals Page
    'approvals.title': 'Approvals',
    'approvals.subtitle': 'Review and approve pending invoices and expenses',
    'approvals.pendingInvoices': 'Pending Invoices',
    'approvals.pendingExpenses': 'Pending Expenses',
    'approvals.profileRequests': 'Employee Profile Update Requests',
    'approvals.noItems': 'No items pending approval',
    'approvals.noInvoices': 'No invoices pending your approval',
    'approvals.noExpenses': 'No expenses pending your approval',
    'approvals.noProfileRequests': 'No profile update requests pending',
    'approvals.approve': 'Approve',
    'approvals.reject': 'Reject',
    'approvals.serial': 'Serial',
    'approvals.submittedBy': 'Submitted By',
    'approvals.rejectReason': 'Rejection Reason',
    'approvals.rejectReasonPlaceholder': 'Enter reason for rejection...',
    'approvals.rejectTitle': 'Reject Item',
    'approvals.rejectDescription': 'Please provide a reason for rejection:',
    'approvals.rejectPlaceholder': 'Enter rejection reason...',
    'approvals.accountantApproval': 'Accountant Approval',
    'approvals.adminApproval': 'Admin Approval',
    'approvals.accountantLevel': 'Level 1 (Accountant)',
    'approvals.adminLevel': 'Level 2 (Admin Final)',
    'approvals.awaitingAccountant': 'Awaiting Accountant',
    'approvals.awaitingAdmin': 'Awaiting Admin',
    'approvals.approved': 'Approved',
    'approvals.rejected': 'Rejected',
    
    // VAT Reports Page
    'vatReports.title': 'VAT Returns',
    'vatReports.subtitle': 'Generate VAT returns for IRD submission',
    'vatReports.irdSummary': 'IRD VAT Return Summary',
    'vatReports.totalSales': 'Total Sales (Box 1)',
    'vatReports.outputVat': 'Output VAT (Box 2)',
    'vatReports.totalPurchases': 'Total Purchases (Box 3)',
    'vatReports.inputVat': 'Input VAT (Box 4)',
    'vatReports.netVatPayable': 'Net VAT Payable (Box 5)',
    'vatReports.vatRefundable': 'VAT Refundable (Box 6)',
    'vatReports.salesInvoices': 'Output VAT - Sales Invoices',
    'vatReports.expensesInput': 'Input VAT - Expenses',
    
    // Employee Portal Page
    'employeePortal.title': 'Employee Portal',
    'employeePortal.subtitle': 'View your payslips and manage your profile',
    'employeePortal.welcome': 'Welcome',
    'employeePortal.profile': 'My Profile',
    'employeePortal.payslips': 'Payslips',
    'employeePortal.myProfile': 'My Profile',
    'employeePortal.myPayslips': 'My Payslips',
    'employeePortal.updateRequests': 'Update Requests',
    'employeePortal.personalInfo': 'Personal Information',
    'employeePortal.bankDetails': 'Bank Details',
    'employeePortal.bankInfo': 'Bank Information',
    'employeePortal.requestUpdate': 'Request Update',
    'employeePortal.submitRequest': 'Submit Request',
    'employeePortal.pendingRequests': 'Pending Requests',
    'employeePortal.noPayslips': 'No payslips available',
    'employeePortal.noRequests': 'No update requests',
    'employeePortal.requestedChanges': 'Requested Changes',
    'employeePortal.reviewNotes': 'Notes',
    'employeePortal.downloadPayslip': 'Download Payslip',
    'employeePortal.taxDocuments': 'Tax Documents',
    'employeePortal.updatePending': 'Your update request is pending approval',
    'employeePortal.updateApproved': 'Update approved',
    'employeePortal.updateRejected': 'Update rejected',
    
    // Employee Login Page
    'employeeLogin.title': 'Employee Portal',
    'employeeLogin.subtitle': 'Access your payslips and personal information',
    'employeeLogin.login': 'Employee Login',
    'employeeLogin.register': 'Register',
    'employeeLogin.employeeId': 'Employee ID',
    'employeeLogin.adminLogin': 'Admin/Accountant Login',
    
    // Additional invoice labels
    'invoices.view': 'View',
    'invoices.createNew': 'Create New Invoice',
    'invoices.currency': 'Currency',
    'invoices.issueDate': 'Issue Date',
    'invoices.lineItems': 'Line Items',
    'invoices.quantity': 'Quantity',
    'invoices.rate': 'Rate',
    'invoices.tax': 'Tax',
    'invoices.discount': 'Discount',
    'invoices.notes': 'Notes',
    'invoices.selectClient': 'Select Client',
    'invoices.noInvoices': 'No invoices found',
    'invoices.selectBank': 'Select Bank Account',
    'invoices.selectBankDesc': 'Select the bank account for payment',
    'invoices.attachment': 'Attachment',
    'invoices.receipt': 'Receipt',
    'invoices.uploading': 'Uploading...',
    'invoices.addLine': 'Add Line',
    'invoices.subtotal': 'Subtotal',
    'invoices.total': 'Total',
    'invoices.delete': 'Delete',
    
    
    // Additional expense labels
    'expenses.createNew': 'Add New Expense',
    'expenses.amount': 'Amount',
    'expenses.currency': 'Currency',
    'expenses.date': 'Date',
    'expenses.paymentMethod': 'Payment Method',
    'expenses.selectVendor': 'Select Vendor',
    'expenses.selectBank': 'Select Bank',
    'expenses.noExpenses': 'No expenses found',
    'expenses.bill': 'Bill',
    'expenses.receipt': 'Receipt',
    'expenses.uploading': 'Uploading...',
    'expenses.delete': 'Delete',
    
    
    // Additional employee labels
    'employees.addNew': 'Add New Employee',
    'employees.editTitle': 'Edit Employee',
    'employees.fullName': 'Full Name',
    'employees.email': 'Email',
    'employees.phone': 'Phone',
    'employees.nic': 'NIC',
    'employees.status': 'Status',
    'employees.address': 'Address',
    'employees.joinDate': 'Join Date',
    'employees.active': 'Active',
    'employees.inactive': 'Inactive',
    'employees.noEmployees': 'No employees found',
    'employees.apitScenario': 'APIT Scenario',
    'employees.scenarioEmployee': 'Scenario A (Employee Pays APIT)',
    'employees.scenarioEmployer': 'Scenario B (Employer Pays APIT)',
    'employees.salaryPreview': 'Salary Preview',
    'employees.grossSalary': 'Gross Salary',
    'employees.deductions': 'Deductions',
    'employees.epfEmployee': 'EPF (Employee)',
    'employees.apit': 'APIT',
    'employees.stampFee': 'Stamp Fee',
    'employees.netSalary': 'Net Salary',
    'employees.employerCosts': 'Employer Costs',
    'employees.epfEmployer': 'EPF (Employer)',
    'employees.etf': 'ETF',
    'employees.totalCTC': 'Total CTC',
    'employees.epfRates': 'EPF/ETF Rates (from Tax Config)',
    'employees.edit': 'Edit',
    'employees.delete': 'Delete',
    'employees.linkUserAccount': 'Link to User Account',
    'employees.noUserLink': '-- No linked user --',
    'employees.linkUserHelp': 'Link this employee to a user account for portal access',
    
    
    // Additional bank labels
    'banks.branchLabel': 'Branch',
    
    // Additional tax config labels
    'taxConfig.ongoing': 'Ongoing',
    
    // Additional user labels
    'users.linkedEmployee': 'Linked Employee',
    
    // Common additions
    'common.view': 'View',
    'common.required': 'Required',
    'serial': 'Serial',
    'client': 'Client',
    'vendor': 'Vendor',
    'subtotal': 'Subtotal',
    'vatAmount': 'VAT Amount',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.masters': '主数据',
    'nav.clients': '客户',
    'nav.vendors': '供应商',
    'nav.banks': '银行',
    'nav.taxConfig': '税务配置',
    'nav.bookkeeping': '记账',
    'nav.invoices': '发票',
    'nav.expenses': '费用',
    'nav.transactions': '交易',
    'nav.financialReports': '财务报告',
    'nav.taxReports': '税务报告',
    'nav.salary': '工资',
    'nav.employees': '员工',
    'nav.payroll': '工资单',
    'nav.users': '用户',
    'nav.userGuide': '用户指南',
    'nav.translations': '翻译管理',
    'nav.approvals': '审批',
    'nav.vatReports': '增值税报告',
    'nav.employeePortal': '员工门户',
    'nav.settings': '设置',
    'nav.signOut': '退出登录',
    
    // Settings
    'settings.title': '设置',
    'settings.subtitle': '管理您的账户和应用程序设置',
    'settings.profile': '个人资料',
    'settings.changePassword': '修改密码',
    'settings.company': '公司',
    'settings.defaults': '默认设置',
    'settings.emailConfig': '邮箱',
    'settings.profileInfo': '个人资料信息',
    'settings.fullName': '全名',
    'settings.profileEmail': '邮箱',
    'settings.role': '角色',
    'settings.currentPassword': '当前密码',
    'settings.newPassword': '新密码',
    'settings.confirmPassword': '确认新密码',
    'settings.updatePassword': '更新密码',
    'settings.companyInfo': '公司信息',
    'settings.companyName': '公司名称',
    'settings.taxNumber': '税务登记号',
    'settings.companyAddress': '公司地址',
    'settings.companyPhone': '电话号码',
    'settings.companyEmail': '邮箱',
    'settings.currency': '默认货币',
    'settings.dateFormat': '日期格式',
    'settings.fiscalYearStart': '财政年度开始',
    'settings.defaultSettings': '默认设置',
    'settings.paymentTerms': '默认付款期限（天）',
    'settings.invoiceDueDays': '发票到期天数',
    'settings.defaultCurrency': '默认货币',
    'settings.stampFee': '印花税（卢比）',
    'settings.preferences': '偏好设置',
    'settings.emailNotifications': '邮件通知',
    'settings.emailNotificationsDesc': '为重要事件发送邮件通知',
    'settings.autoApprove': '自动批准管理员交易',
    'settings.autoApproveDesc': '自动批准管理员用户创建的交易',
    'settings.emailConfiguration': '邮箱配置',
    
    // Pending Approval Page
    'pending.title': '账户待审批',
    'pending.message': '您的账户已成功创建。请等待管理员分配您的角色后才能访问系统。',
    'pending.loggedAs': '登录账户',
    'pending.contactAdmin': '如果您认为这是一个错误，请联系您的系统管理员。',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.import': '导入',
    'common.loading': '加载中...',
    'common.noData': '暂无数据',
    'common.actions': '操作',
    'common.status': '状态',
    'common.date': '日期',
    'common.amount': '金额',
    'common.description': '描述',
    'common.name': '名称',
    'common.email': '邮箱',
    'common.phone': '电话',
    'common.address': '地址',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.yes': '是',
    'common.no': '否',
    'common.clear': '清除',
    'common.apply': '应用',
    'common.applyFilter': '应用筛选',
    'common.filterByDate': '按日期筛选',
    'common.startDate': '开始日期',
    'common.endDate': '结束日期',
    'common.showing': '显示数据从',
    'common.to': '至',
    'common.select': '选择',
    
    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.welcome': '欢迎回来！这是您的财务概览。',
    'dashboard.totalRevenue': '总收入',
    'dashboard.totalExpenses': '总支出',
    'dashboard.netProfit': '净利润',
    'dashboard.pendingInvoices': '待处理发票',
    'dashboard.payroll': '工资支出',
    'dashboard.recentTransactions': '最近交易',
    'dashboard.fromDate': '开始日期',
    'dashboard.toDate': '结束日期',
    'dashboard.quickActions': '快捷操作',
    'dashboard.financialSummary': '财务摘要',
    'dashboard.createInvoice': '创建发票',
    'dashboard.createInvoiceDesc': '为客户生成新发票',
    'dashboard.recordExpense': '记录费用',
    'dashboard.recordExpenseDesc': '记录新的业务费用',
    'dashboard.processPayroll': '处理工资',
    'dashboard.processPayrollDesc': '生成和管理员工工资',
    'dashboard.viewReports': '查看报告',
    'dashboard.viewReportsDesc': '分析您的财务数据',
    'dashboard.revenue': '收入',
    'dashboard.expenses': '支出',
    'dashboard.filterByDate': '按日期筛选',
    'dashboard.startDate': '开始日期',
    'dashboard.endDate': '结束日期',
    'dashboard.applyFilter': '应用筛选',
    'dashboard.clear': '清除',
    'dashboard.showingDataFrom': '显示数据从',
    'dashboard.to': '至',
    'dashboard.noFinancialData': '暂无财务数据',
    
    // Clients
    'clients.title': '客户管理',
    'clients.description': '管理您的客户信息',
    'clients.addClient': '添加客户',
    'clients.editClient': '编辑客户',
    'clients.clientName': '客户名称',
    'clients.contactPerson': '联系人',
    
    // Vendors
    'vendors.title': '供应商管理',
    'vendors.description': '管理您的供应商信息',
    'vendors.addVendor': '添加供应商',
    'vendors.editVendor': '编辑供应商',
    'vendors.vendorName': '供应商名称',
    
    // Banks
    'banks.title': '银行账户',
    'banks.addBank': '添加银行账户',
    'banks.editBank': '编辑银行账户',
    'banks.bankName': '银行名称',
    'banks.accountName': '账户名称',
    'banks.accountNumber': '账户号码',
    'banks.branch': '支行',
    'banks.balance': '当前余额',
    'banks.balanceReadonly': '编辑时余额为只读。请通过交易更新。',
    
    // Invoices
    'invoices.title': '发票管理',
    'invoices.addInvoice': '添加发票',
    'invoices.editInvoice': '编辑发票',
    'invoices.invoiceNumber': '发票号码',
    'invoices.client': '客户',
    'invoices.dueDate': '到期日',
    'invoices.paid': '已付款',
    'invoices.pending': '待处理',
    'invoices.draft': '草稿',
    'invoices.files': '文件',
    'invoices.createInvoice': '创建发票',
    
    // Expenses
    'expenses.title': '费用管理',
    'expenses.addExpense': '添加费用',
    'expenses.editExpense': '编辑费用',
    'expenses.category': '类别',
    'expenses.vendor': '供应商',
    'expenses.approved': '已批准',
    'expenses.pending': '待处理',
    'expenses.expenseNo': '费用编号',
    'expenses.files': '文件',
    
    // Employees
    'employees.title': '员工管理',
    'employees.addEmployee': '添加员工',
    'employees.editEmployee': '编辑员工',
    'employees.employeeName': '员工姓名',
    'employees.designation': '职位',
    'employees.basicSalary': '基本工资',
    'employees.epfNo': '公积金号',
    'employees.employeeId': '员工编号',
    'employees.department': '部门',
    
    // Payroll
    'payroll.title': '工资管理',
    'payroll.generatePayroll': '生成工资单',
    'payroll.processPayroll': '处理工资',
    'payroll.payrollRuns': '工资记录',
    'payroll.month': '月份',
    'payroll.year': '年份',
    'payroll.grossSalary': '总工资',
    'payroll.netSalary': '净工资',
    'payroll.deductions': '扣除',
    'payroll.transportAllowance': '交通津贴',
    'payroll.performanceSalary': '绩效工资',
    'payroll.description': '为员工生成和管理工资记录',
    'payroll.runNumber': '编号',
    'payroll.period': '期间',
    'payroll.ctc': '总成本',
    'payroll.status': '状态',
    'payroll.attendanceData': '考勤数据',
    'payroll.downloadTemplate': '下载模板',
    'payroll.workingDaysInMonth': '本月工作天数',
    'payroll.uploadAttendance': '上传考勤文件',
    'payroll.chooseFile': '选择Excel文件',
    'payroll.attendanceLoaded': '已加载 {count} 名员工的考勤',
    'payroll.daysAttended': '出勤天数',
    'payroll.absent': '缺勤',
    'payroll.attendanceDeduction': '考勤扣款',
    'payroll.otherDeduction': '其他扣款',
    'payroll.uploadAttendanceFirst': '请先上传考勤文件再继续',
    'payroll.attendanceWarnings': '考勤警告',
    'payroll.attendanceHistoryTitle': '历史考勤记录',
    'payroll.attendanceHistoryNote': '显示此期间上次工资单的考勤记录。',
    'payroll.loadingHistory': '正在加载考勤历史...',
    'payroll.employee': '员工',
    'payroll.workingDays': '工作天数',
    'payroll.sickLeave': '病假',
    'payroll.casualLeave': '事假',
    'payroll.annualLeave': '年假',
    'payroll.unpaidLeave': '无薪假',
    'payroll.otherLeave': '其他假',
    'payroll.leaveNotes': '请假备注',
    'payroll.leaveBreakdown': '假期明细',
    'payroll.paidLeave': '带薪假期',
    
    // Users
    'users.title': '用户管理',
    'users.addUser': '添加用户',
    'users.editUser': '编辑用户',
    'users.fullName': '全名',
    'users.role': '角色',
    'users.admin': '管理员',
    'users.accountant': '会计',
    'users.employee': '员工',
    'users.unmarked': '未标记',
    'users.unmarkedUsersReminder': '需要操作：分配用户角色',
    'users.unmarkedUsersMessage': '位用户正在等待角色分配。请分配角色以启用其访问权限。',
    'users.pending': '待处理',
    'users.pleaseAssignRole': '请为此用户分配角色',
    'users.passwordHint': '留空以保持当前密码',
    'users.linkEmployee': '关联员工',
    'users.linkEmployeeHint': '仅显示未关联账户的员工',
    'users.rolePermissionsTitle': '角色权限',
    'users.usersCount': '位用户',
    'users.rolePermissions.fullAccess': '完全系统访问权限',
    'users.rolePermissions.manageUsers': '管理用户和角色',
    'users.rolePermissions.taxConfig': '税务配置',
    'users.rolePermissions.employees': '员工管理',
    'users.rolePermissions.payroll': '工资处理',
    'users.rolePermissions.approvals': '审批交易',
    'users.rolePermissions.invoices': '创建和管理发票',
    'users.rolePermissions.expenses': '记录和管理费用',
    'users.rolePermissions.reports': '查看财务报告',
    'users.rolePermissions.clients': '管理客户和供应商',
    'users.rolePermissions.banks': '查看银行账户',
    'users.rolePermissions.viewPayslips': '查看个人工资单',
    'users.rolePermissions.viewProfile': '查看个人资料',
    'users.rolePermissions.requestUpdates': '请求资料更新',
    'users.editPermissions': '编辑权限',
    'users.addPermission': '添加权限...',
    'users.resetToDefaults': '重置为默认',
    'users.confirmResetPermissions': '将所有权限重置为默认值？',
    'users.selectPermissions': '选择权限',
    'users.customPermissions': '自定义权限',
    'users.addCustomPermission': '添加自定义权限...',
    'users.permissionsSelected': '个权限已选择',
    
    // Vendors
    'vendors.taxId': '税号',
    
    // Translations
    'translations.title': '翻译管理',
    'translations.key': '键',
    'translations.english': '英语',
    'translations.chinese': '中文（简体）',
    'translations.searchPlaceholder': '搜索翻译...',
    'translations.saveChanges': '保存更改',
    'translations.resetToDefault': '重置为默认',
    'translations.saved': '翻译保存成功',
    'translations.language': '语言',
    
    // Login
    'login.title': '登录',
    'login.email': '邮箱地址',
    'login.password': '密码',
    'login.signIn': '登录',
    'login.forgotPassword': '忘记密码？',
    'login.accounts': '账户',
    'login.tagline1': '简化您的',
    'login.tagline2': '财务管理',
    'login.description': '完整的会计解决方案，包括发票、费用、工资和税务合规 - 全部集成在一个平台。',
    'login.createAccount': '创建账户',
    'login.welcomeBack': '欢迎回来',
    'login.signupSubtitle': '立即开始管理您的财务',
    'login.loginSubtitle': '登录以继续访问您的仪表板',
    'login.enterFullName': '输入您的全名',
    'login.creatingAccount': '正在创建账户...',
    'login.signingIn': '正在登录...',
    'login.haveAccount': '已有账户？',
    'login.noAccount': '没有账户？',
    'login.signInInstead': '改为登录',
    'login.createAccountLink': '创建账户',
    'login.allRightsReserved': '版权所有。',
    
    // Forgot Password
    'forgotPassword.title': '忘记密码？',
    'forgotPassword.subtitle': '输入您的邮箱以接收重置链接',
    'forgotPassword.resetYour': '重置您的',
    'forgotPassword.password': '密码',
    'forgotPassword.description': '别担心，这种事每个人都会遇到。输入您的邮箱，我们将发送重置链接。',
    'forgotPassword.sendResetLink': '发送重置链接',
    'forgotPassword.sending': '发送中...',
    'forgotPassword.emailSent': '邮件已发送！',
    'forgotPassword.checkInbox': '请查看您的收件箱获取密码重置链接。链接将在1小时后过期。',
    'forgotPassword.backToLogin': '返回登录',
    'forgotPassword.error': '发送重置邮件失败。请重试。',
    
    // Reset Password
    'resetPassword.title': '重置密码',
    'resetPassword.subtitle': '在下方输入您的新密码',
    'resetPassword.createNew': '创建新',
    'resetPassword.password': '密码',
    'resetPassword.description': '请选择一个您以前没有使用过的强密码。',
    'resetPassword.newPassword': '新密码',
    'resetPassword.confirmPassword': '确认密码',
    'resetPassword.resetPassword': '重置密码',
    'resetPassword.resetting': '重置中...',
    'resetPassword.success': '密码已重置！',
    'resetPassword.redirecting': '您的密码已成功重置。正在跳转到登录页面...',
    'resetPassword.error': '重置密码失败。链接可能已过期。',
    'resetPassword.passwordMismatch': '两次输入的密码不一致',
    'resetPassword.passwordTooShort': '密码至少需要8个字符',
    'resetPassword.invalidLink': '无效的重置链接',
    'resetPassword.invalidLinkDescription': '此密码重置链接无效或已过期。',
    'resetPassword.requestNewLink': '请求新链接',
    'login.loginFailed': '登录失败。请检查您的邮箱和密码。',
    'login.signupFailed': '注册失败。请重试。',
    
    // Guide
    'guide.title': '用户指南',
    'guide.gettingStarted': '开始使用',
    'guide.gettingStartedContent': '欢迎使用VeloSync！这个全面的会计系统帮助您管理所有财务运营，包括客户、发票、费用、工资和报告。使用导航菜单根据您的角色权限访问不同的模块。',
    'guide.managingClients': '管理客户',
    'guide.managingClientsContent': '创建和管理客户记录，包括完整的联系信息：姓名、邮箱、电话、地址和税号。导航到客户页面添加新客户、编辑现有记录或删除不再需要的客户。',
    'guide.managingVendors': '管理供应商',
    'guide.managingVendorsContent': '维护所有供应商和服务提供商的记录。添加供应商详细信息，包括名称、联系人、邮箱、电话和地址。供应商可以与费用关联以便更好地跟踪和报告。',
    'guide.bankAccounts': '银行账户',
    'guide.bankAccountsContent': '设置和管理多个银行账户，包括账户号码、银行名称和分行详情。跟踪开户余额（仅在创建时设置）。处理发票、费用和工资时，银行余额会自动更新。',
    'guide.creatingInvoices': '创建发票',
    'guide.creatingInvoicesContent': '生成带有自动序列号（INV-XXXX）的专业发票。添加多个行项目，包括描述、数量、费率和税率。附上报价单和收据等支持文件。',
    'guide.trackingExpenses': '跟踪费用',
    'guide.trackingExpensesContent': '记录带有自动序列号（EXP-XXXX）的业务费用。分类费用、关联供应商、指定付款方式（现金/银行/卡）并上传账单和收据。',
    'guide.employeeManagement': '员工管理（仅管理员）',
    'guide.employeeManagementContent': '管理员工记录，包括个人详情、就业信息和工资组成部分。设置基本工资和津贴。EPF和ETF费率从活动的税务配置自动填充。',
    'guide.payrollProcessing': '工资处理（仅管理员）',
    'guide.payrollProcessingContent': '批量处理多名员工的工资。选择员工并在处理前预览计算。在预览中，您可以编辑津贴和绩效奖金。工资包括EPF、ETF、APIT和印花费。',
    'guide.apitScenarios': 'APIT场景说明',
    'guide.apitScenariosContent': 'APIT（预扣个人所得税）使用基于税级的税率和标准扣除额为每位员工计算一次。场景A - 员工支付APIT（从工资中扣除），场景B - 雇主支付APIT（添加到雇主成本）。',
    'guide.taxConfiguration': '税务配置（仅管理员）',
    'guide.taxConfigurationContent': '配置税率，包括EPF员工费率、EPF雇主费率、ETF费率和印花费。这些配置在添加新员工时自动应用。',
    'guide.taxReports': '税务报告',
    'guide.taxReportsContent': '生成提交给税务局的税务合规报告。报告包括：已付发票的总收入、已批准费用的总支出、APIT扣除和工资法定贡献。',
    'guide.transactionsTracking': '交易跟踪',
    'guide.transactionsTrackingContent': '在一个地方查看所有财务交易，分为两个标签：所有交易显示发票、费用和工资摘要。银行交易标签显示所有银行借贷记录。',
    'guide.financialReports': '财务报告',
    'guide.financialReportsContent': '访问三个综合报告视图：概览（总收入、支出、利润）、损益表和费用明细。报告仅包括已确认的交易。',
    'guide.userManagement': '用户管理（仅管理员）',
    'guide.userManagementContent': '使用基于角色的访问控制管理系统用户。创建管理员或会计角色的用户。管理员用户拥有完全访问权限。会计用户访问受限。',
    'guide.fileAttachments': '文件附件',
    'guide.fileAttachmentsContent': '为发票（附件和收据）和费用（账单和收据）上传支持文件。文件安全存储。删除发票或费用时，相关文件会自动删除。',
    'guide.auditLogs': '审计日志',
    'guide.auditLogsContent': '所有创建、更新和删除操作都会自动记录用户信息和时间戳。审计日志有助于跟踪更改和维护问责制。',
    'guide.employeePortal': '员工门户',
    'guide.employeePortalContent': '员工可以通过自助门户查看工资单、税务文件和管理个人信息。员工可以使用员工ID和电子邮件自行注册，或者管理员可以创建账户并链接到员工记录。个人资料更新需要管理员批准。',
    'guide.payrollApprovalWorkflow': '工资审批流程',
    'guide.payrollApprovalWorkflowContent': '会计可以创建工资运行，需要管理员批准后才能处理。管理员用户可以批准或拒绝提交的工资。批准后，可以处理工资，这将创建法定缴款的费用记录并更新银行余额。',
    'guide.attendanceTracking': '考勤跟踪',
    'guide.attendanceTrackingContent': '在处理工资之前通过Excel文件上传员工考勤。模板包括员工ID、姓名、工作天数、出勤天数，支持半天。系统验证数据并自动计算基于考勤的扣款。假期类型包括病假、事假、年假、无薪假和其他。',
    'guide.vatFiling': '增值税申报',
    'guide.vatFilingContent': '为IRD提交生成增值税申报表。增值税固定为18%。系统跟踪发票上的增值税并生成增值税申报表，显示销项税（销售）、进项税（采购）和应缴净增值税。',
    'guide.approvalWorkflows': '审批流程',
    'guide.approvalWorkflowsContent': '会计创建的发票和费用需要管理员批准。管理员创建的交易自动批准。审批页面（仅限管理员）显示所有待审核项目。会计的工资运行也需要管理员批准。',
    'guide.rolePermissions': '角色权限',
    'guide.rolePermissionsContent': '管理员可以通过用户管理为每个角色（管理员、会计、员工）自定义权限。无需代码更改即可动态添加、删除或编辑权限。如有需要可重置为默认值。',
    'guide.multiLanguage': '多语言支持',
    'guide.multiLanguageContent': '使用语言选择器在英语和中文之间切换。管理员可以通过翻译管理页面管理翻译，无需代码更改即可更新UI标签。',
    'guide.passwordRecovery': '密码恢复',
    'guide.passwordRecoveryContent': '使用登录页面上的"忘记密码？"链接接收密码重置电子邮件。点击电子邮件中的链接设置新密码。重置链接在1小时后过期。',
    
    // Tax Configuration
    'taxConfig.title': '税务配置',
    'taxConfig.addConfig': '添加税务配置',
    'taxConfig.editConfig': '编辑税务配置',
    'taxConfig.seedDefault': '加载默认配置',
    'taxConfig.seeding': '加载中...',
    'taxConfig.type': '类型',
    'taxConfig.taxType': '税种',
    'taxConfig.rate': '费率',
    'taxConfig.from': '从',
    'taxConfig.to': '至',
    'taxConfig.applicableFrom': '生效日期',
    'taxConfig.applicableTo': '截止日期（可选）',
    'taxConfig.active': '活动',
    'taxConfig.inactive': '停用',
    'taxConfig.noConfigs': '未找到税务配置。点击"加载默认配置"以加载斯里兰卡默认值。',
    
    // Tax Reports
    'taxReports.title': '税务报告',
    'taxReports.generateReport': '生成报告',
    'taxReports.companyName': '公司名称',
    'taxReports.companyTIN': '税务识别号（TIN）',
    'taxReports.companyAddress': '公司地址',
    'taxReports.generating': '生成中...',
    'taxReports.downloadPDF': '下载税务报告PDF',
    'taxReports.infoText': '这将生成一份全面的税务报告，包括所选期间的收入、支出、增值税和工资税信息。该报告可提交给斯里兰卡税务局。',
    
    // Transactions Page
    'transactions': '交易',
    'totalIncome': '总收入',
    'totalExpenses': '总支出',
    'totalPayroll': '总工资',
    'netBalance': '净余额',
    'allTransactions': '所有交易',
    'bankTransactions': '银行交易',
    'all': '全部',
    'income': '收入',
    'expenses': '支出',
    'payroll': '工资',
    'date': '日期',
    'type': '类型',
    'category': '类别',
    'description': '描述',
    'reference': '参考',
    'amount': '金额',
    'bankAccount': '银行账户',
    'credit': '贷方',
    'debit': '借方',
    'expense': '费用',
    
    // Reports Page
    'reports': '报告',
    'reports.title': '报告',
    'overviewReport': '概览报告',
    'overviewReportDesc': '财务摘要和关键指标',
    'profitLoss': '损益表',
    'profitLossDesc': '详细的损益表',
    'expenseBreakdown': '费用明细',
    'expenseBreakdownDesc': '按类别划分的费用',
    'generate': '生成',
    
    // Enhanced Reports Page
    'enhancedReports.overview': '概览',
    'enhancedReports.profitLoss': '损益表',
    'enhancedReports.expensesBreakdown': '费用明细',
    'enhancedReports.totalRevenue': '总收入',
    'enhancedReports.invoices': '张发票',
    'enhancedReports.totalExpenses': '总费用',
    'enhancedReports.expensesLabel': '费用',
    'enhancedReports.payrollCosts': '工资成本',
    'enhancedReports.payrollEntries': '条工资记录',
    'enhancedReports.totalCosts': '总成本',
    'enhancedReports.expensesPlusPayroll': '费用 + 工资',
    'enhancedReports.netProfit': '净利润',
    'enhancedReports.profit': '盈利',
    'enhancedReports.loss': '亏损',
    'enhancedReports.revenue': '收入',
    'enhancedReports.period': '期间',
    'enhancedReports.unknown': '未知',
    'enhancedReports.totalPayroll': '工资总计',
    'enhancedReports.netProfitLoss': '净利润/亏损',
    'enhancedReports.count': '数量',
    'enhancedReports.totalAmount': '总金额',
    'enhancedReports.percentage': '百分比',
    'enhancedReports.total': '合计',
    
    // Approvals Page
    'approvals.title': '审批',
    'approvals.subtitle': '审核和批准待处理的发票和费用',
    'approvals.pendingInvoices': '待审批发票',
    'approvals.pendingExpenses': '待审批费用',
    'approvals.profileRequests': '员工资料更新请求',
    'approvals.noItems': '没有待审批项目',
    'approvals.noInvoices': '没有待审批的发票',
    'approvals.noExpenses': '没有待审批的费用',
    'approvals.noProfileRequests': '没有待处理的资料更新请求',
    'approvals.approve': '批准',
    'approvals.reject': '拒绝',
    'approvals.serial': '编号',
    'approvals.submittedBy': '提交人',
    'approvals.rejectReason': '拒绝原因',
    'approvals.rejectReasonPlaceholder': '输入拒绝原因...',
    'approvals.rejectTitle': '拒绝项目',
    'approvals.rejectDescription': '请提供拒绝原因：',
    'approvals.rejectPlaceholder': '输入拒绝原因...',
    'approvals.accountantApproval': '会计审批',
    'approvals.adminApproval': '管理员审批',
    'approvals.accountantLevel': '第一级 (会计)',
    'approvals.adminLevel': '第二级 (管理员最终)',
    'approvals.awaitingAccountant': '等待会计审批',
    'approvals.awaitingAdmin': '等待管理员审批',
    'approvals.approved': '已批准',
    'approvals.rejected': '已拒绝',
    
    // VAT Reports Page
    'vatReports.title': '增值税申报',
    'vatReports.subtitle': '生成增值税申报表提交给税务局',
    'vatReports.irdSummary': '税务局增值税申报摘要',
    'vatReports.totalSales': '销售总额 (Box 1)',
    'vatReports.outputVat': '销项税 (Box 2)',
    'vatReports.totalPurchases': '采购总额 (Box 3)',
    'vatReports.inputVat': '进项税 (Box 4)',
    'vatReports.netVatPayable': '应缴增值税 (Box 5)',
    'vatReports.vatRefundable': '可退增值税 (Box 6)',
    'vatReports.salesInvoices': '销项税 - 销售发票',
    'vatReports.expensesInput': '进项税 - 费用',
    
    // Employee Portal Page
    'employeePortal.title': '员工门户',
    'employeePortal.subtitle': '查看工资单和管理个人资料',
    'employeePortal.welcome': '欢迎',
    'employeePortal.profile': '我的资料',
    'employeePortal.payslips': '工资单',
    'employeePortal.myProfile': '我的资料',
    'employeePortal.myPayslips': '我的工资单',
    'employeePortal.updateRequests': '更新请求',
    'employeePortal.personalInfo': '个人信息',
    'employeePortal.bankDetails': '银行信息',
    'employeePortal.bankInfo': '银行信息',
    'employeePortal.requestUpdate': '请求更新',
    'employeePortal.submitRequest': '提交请求',
    'employeePortal.pendingRequests': '待处理请求',
    'employeePortal.noPayslips': '暂无工资单',
    'employeePortal.noRequests': '暂无更新请求',
    'employeePortal.requestedChanges': '请求的更改',
    'employeePortal.reviewNotes': '备注',
    'employeePortal.downloadPayslip': '下载工资单',
    'employeePortal.taxDocuments': '税务文件',
    'employeePortal.updatePending': '您的更新请求正在等待审批',
    'employeePortal.updateApproved': '更新已批准',
    'employeePortal.updateRejected': '更新已拒绝',
    
    // Employee Login Page
    'employeeLogin.title': '员工门户',
    'employeeLogin.subtitle': '访问您的工资单和个人信息',
    'employeeLogin.login': '员工登录',
    'employeeLogin.register': '注册',
    'employeeLogin.employeeId': '员工编号',
    'employeeLogin.adminLogin': '管理员/会计登录',
    
    // Common additions
    'startDate': '开始日期',
    'endDate': '结束日期',
    'serial': '序号',
    'client': '客户',
    'vendor': '供应商',
    'subtotal': '小计',
    'vatAmount': '增值税金额',
    
    // Additional invoice labels
    'invoices.view': '查看',
    'invoices.createNew': '创建新发票',
    'invoices.currency': '货币',
    'invoices.issueDate': '开票日期',
    'invoices.lineItems': '明细项目',
    'invoices.quantity': '数量',
    'invoices.rate': '单价',
    'invoices.tax': '税',
    'invoices.discount': '折扣',
    'invoices.notes': '备注',
    'invoices.selectClient': '选择客户',
    'invoices.noInvoices': '暂无发票',
    'invoices.selectBank': '选择银行账户',
    'invoices.selectBankDesc': '选择用于收款的银行账户',
    'invoices.attachment': '发票附件',
    'invoices.receipt': '收据',
    'invoices.uploading': '上传中...',
    'invoices.addLine': '添加行',
    'invoices.subtotal': '小计',
    'invoices.total': '总计',
    'invoices.delete': '删除',
    
    // Additional expense labels
    'expenses.createNew': '添加新费用',
    'expenses.amount': '金额',
    'expenses.currency': '货币',
    'expenses.date': '日期',
    'expenses.paymentMethod': '付款方式',
    'expenses.selectVendor': '选择供应商',
    'expenses.selectBank': '选择银行',
    'expenses.noExpenses': '暂无费用',
    'expenses.bill': '账单',
    'expenses.receipt': '收据',
    'expenses.uploading': '上传中...',
    'expenses.delete': '删除',
    
    // Additional employee labels
    'employees.addNew': '添加新员工',
    'employees.editTitle': '编辑员工',
    'employees.fullName': '全名',
    'employees.email': '邮箱',
    'employees.phone': '电话',
    'employees.nic': '身份证号',
    'employees.status': '状态',
    'employees.address': '地址',
    'employees.joinDate': '入职日期',
    'employees.active': '在职',
    'employees.inactive': '离职',
    'employees.noEmployees': '暂无员工',
    'employees.apitScenario': 'APIT场景',
    'employees.scenarioEmployee': '场景A（员工缴纳APIT）',
    'employees.scenarioEmployer': '场景B（雇主缴纳APIT）',
    'employees.salaryPreview': '工资预览',
    'employees.grossSalary': '总工资',
    'employees.deductions': '扣除',
    'employees.epfEmployee': 'EPF（员工）',
    'employees.apit': 'APIT',
    'employees.stampFee': '印花费',
    'employees.netSalary': '净工资',
    'employees.employerCosts': '雇主成本',
    'employees.epfEmployer': 'EPF（雇主）',
    'employees.etf': 'ETF',
    'employees.totalCTC': '总人力成本',
    'employees.epfRates': 'EPF/ETF费率（来自税务配置）',
    'employees.edit': '编辑',
    'employees.delete': '删除',
    'employees.linkUserAccount': '关联用户账户',
    'employees.noUserLink': '-- 无关联用户 --',
    'employees.linkUserHelp': '将此员工关联到用户账户以便访问门户',
    
    // Additional bank labels
    'banks.branchLabel': '支行',
    
    // Additional tax config labels
    'taxConfig.ongoing': '持续中',
    
    // Additional user labels
    'users.linkedEmployee': '关联员工',
    
    // Common view and required
    'common.view': '查看',
    'common.required': '必填',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Version number to force translation reset when structure changes
const TRANSLATIONS_VERSION = '2.4';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });
  
  const [translations, setTranslations] = useState<Record<Language, Translations>>(() => {
    const savedVersion = localStorage.getItem('translations_version');
    
    // If version mismatch, reset to defaults to fix any swapped translations
    if (savedVersion !== TRANSLATIONS_VERSION) {
      localStorage.removeItem('translations');
      localStorage.setItem('translations_version', TRANSLATIONS_VERSION);
      return defaultTranslations;
    }
    
    const saved = localStorage.getItem('translations');
    if (saved) {
      const parsed = JSON.parse(saved);
      // Merge saved translations with defaults to ensure new keys are always available
      return {
        en: { ...defaultTranslations.en, ...parsed.en },
        zh: { ...defaultTranslations.zh, ...parsed.zh }
      };
    }
    return defaultTranslations;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('translations', JSON.stringify(translations));
  }, [translations]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const updateTranslation = (lang: Language, key: string, value: string) => {
    setTranslations(prev => ({
      ...prev,
      [lang]: {
        ...prev[lang],
        [key]: value
      }
    }));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations, updateTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { defaultTranslations };
